tmrin/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name="home"),
    path('', include("user.urls", namespace='users'))
]

user/urls.py
from django.urls import path
from .views import register_user, logout, login_user, note_creator, shownotes, edit_notes


app_name = 'user'

urlpatterns = [
    path('register/', register_user, name="register"),
    path('logout/', logout, name="logout"),
    path('login/',login_user, name='login'),
    path('create/', note_creator, name='note_creating'),
    path('profile/', shownotes, name='profile'),
    path('edit_notes/<int:id>', edit_notes, name='edit_notes')
]

user/models.py
from django.db import models
# from django.contrib.auth.models import User

# class Profile(User):
#     subscribers = models.CharField(max_length=255)

user/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core import validators



class RegisterForm(forms.Form):
    user_name = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder': 'لطفا نام کاربری خود را وارد نمایید'}),
        label='نام کاربری',
        validators=[
            validators.MaxLengthValidator(limit_value=20,
                                          message='تعداد کاراکترهای وارد شده نمیتواند بیشتر از 20 باشد'),
            validators.MinLengthValidator(8, 'تعداد کاراکترهای وارد شده نمیتواند کمتر از 8 باشد')
        ]
    )

    email = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder': 'لطفا ایمیل خود را وارد نمایید'}),
        label='ایمیل',
        validators=[
            validators.EmailValidator('ایمیل وارد شده معتبر نمیباشد')
        ]
    )

    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'placeholder': 'لطفا کلمه عبور خود را وارد نمایید'}),
        label='کلمه ی عبور'
    )

    re_password = forms.CharField(
        widget=forms.PasswordInput(attrs={'placeholder': 'لطفا تکرار کلمه عبور خود را وارد نمایید'}),
        label='تکرار کلمه ی عبور'
    )

    def clean_email(self):
        email = self.cleaned_data.get('email')
        is_exists_user_by_email = User.objects.filter(email=email).exists()
        if is_exists_user_by_email:
            raise forms.ValidationError('ایمیل وارد شده تکراری میباشد')

        if len(email) > 20:
            raise forms.ValidationError('تعداد کاراکترهای ایمیل باید کمتر از 20 باشد')

        return email

    def clean_user_name(self):
        user_name = self.cleaned_data.get('user_name')
        is_exists_user_by_username = User.objects.filter(username=user_name).exists()

        if is_exists_user_by_username:
            raise forms.ValidationError('این کاربر قبلا ثبت نام کرده است')

        return user_name

    def clean_re_password(self):
        password = self.cleaned_data.get('password')
        re_password = self.cleaned_data.get('re_password')
        print(password)
        print(re_password)

        if password != re_password:
            raise forms.ValidationError('کلمه های عبور مغایرت دارند')

        return password

    
class LoginForm(forms.Form):
    user_name = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder': 'لطفا نام کاربری خود را وارد نمایید'}),
        label='نام کاربری'
    )

    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'placeholder': 'لطفا کلمه عبور خود را وارد نمایید'}),
        label='کلمه ی عبور'
    )

    def clean_user_name(self):
        user_name = self.cleaned_data.get('user_name')
        is_exists_user = User.objects.filter(username=user_name).exists()
        if not is_exists_user:
            raise forms.ValidationError('کاربری با مشخصات وارد شده ثبت نام نکرده است')

        return user_name

user/views.py
from django.contrib.auth import decorators
from django.contrib.auth.models import User
from django.db.models.fields import AutoField
from django.shortcuts import redirect, render
from .forms import RegisterForm, LoginForm
from django.contrib.auth import authenticate, logout as _logout, login as _login
from django.contrib.auth.decorators import login_required
from note.models import Note
from django.views.decorators.http import require_GET, require_http_methods
from django.http import Http404



def register_user(request):
    register_form = RegisterForm(request.POST or None)

    if register_form.is_valid():
        user_name = register_form.cleaned_data.get('user_name')
        password = register_form.cleaned_data.get('password')
        email = register_form.cleaned_data.get('email')
        User.objects.create_user(username=user_name, email=email, password=password)
        return redirect('/')
    context = {
        'register_form' : register_form
    }
    return render(request, 'user/register.html', context)


def login_user(request):
    login_form = LoginForm(request.POST or None)
    if login_form.is_valid():
        user_name = login_form.cleaned_data.get('user_name')
        password = login_form.cleaned_data.get('password')
        user = authenticate(request, username=user_name, password=password)
        if user is not None:
            _login(request, user)
            return redirect('/')
        else:
            login_form.add_error('user_name', 'کاربری با مشخصات وارد شده یافت نشد')

    context = {
        'login_form': login_form
    }
    return render(request, 'user/login.html', context)


def logout(request):
    _logout(request)
    return redirect('/')


@login_required(login_url="/login")
@require_http_methods(["GET", "POST"])
def note_creator(request):
    user_username = request.user.username
    user = User.objects.get(username=user_username)
    subscribers_get = User.objects.all()
    # print(subscribers_get.username)
    if user is None:
        raise Http404('کاربر مورد نظر یافت نشد')
    if request.method == "GET":
        show_note_form = Note.objects.all()
        context = {
            'show_note_form' : show_note_form,
            'subscribers' : subscribers_get
        }
        return render(request, 'user/create.html', context)
    if request.method == 'POST':
        title = request.POST.get('title')
        description = request.POST.get('description')
        # subscriber_note = request.POST.get('subscribers')
        # subs = list(subscribers_get.values_list("username", flat=True))
        # subs_1 = User.objects.all()
        
        # print(subs_1.username)

        # for elm in subs.username:
        #     if subscriber_note in subs:
        #         subscriber_note = elm
        # Django value error. model field must be an instance
        # subs=User.objects.filter(username=subscriber_note)

        # subs = User.objects.filter(id,username=subscriber_note)
        # print(subs)
        
        # subs = Note.objects.get(subscribers__username=subscriber_note)
        # print(subs)

        writing_note = Note.objects.create(title=title, description = description, writer=user)
        context  = {
            'writing_note' : writing_note,
        }
        return redirect('/')


@login_required(login_url="/login")
def shownotes(request):
    user_username = request.user.username
    user = User.objects.get(username=user_username)
    subscribers = Note.objects.values_list('subscribers', flat=True)
    notes = Note.objects.all().filter(writer=user)
    context = {
        'notes' : notes
    }
    return render(request, 'user/profile.html', context)


@login_required(login_url="/login")
def edit_notes(request, id):
    user_username = request.user.username
    user = User.objects.get(username=user_username)
    note = list(Note.objects.filter(id=id, writer=user))
    subscribers_get = User.objects.all()
    if note is None:
        raise Http404('همچین نوتی یافت نشد')
    
    if request.method == "GET":
        context = {
            'note_detail' : note,
            'subscribers' : subscribers_get
        }
        return render(request, 'user/edit.html', context)
    
    elif request.method == "POST":
        title = request.POST.get('new_title')
        description = request.POST.get('new_description')
        subscribers = request.POST.get("subscribers")
        subs = User.objects.filter(username=subscribers).first()
        # subs = Note.objects.get(subscribers__username=subscribers)
        # print(subs)
        # user.subscribers=subscribers
        # user.save()
        note[0].title = title
        note[0].description = description
        # note[0].subscribers = subs.username
        note[0].save()
        # note.add(user)
        note_delete = Note.objects.get(id=id)

        note_delete.delete()

        

        context = {
            'updating_note' : note,
            'note_delete' : note_delete
        }
        return redirect('user:profile')

user/templates/user/create.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

  <div class = "container">
    <form action="{% url 'users:note_creating' %}" method="post">
      {% csrf_token %}
      <h4>title</h4>
      <div class = "form-group">
        <input type = "text" class = "form-control" 
            id = "exampleFormControlInput1" name="title" placeholder = "title">
      </div>

      <h4>your subscribers</h4>
      <div class = "form-group">
        <select multiple class="custom-select" id = "exampleFormControlSelect2" name='subscribers' type= "text">
          {% for subscriber in subscribers %}
          <option>{{ subscriber }}</option>
          {% endfor %}
        </select>

       
      <h4>note</h4>
      <div class = "form-group">
        <textarea class = "form-control" id = "exampleFormControlTextarea1" name="description" rows = "3"></textarea>
      </div>
      <button type="submit" class="btn btn-success">Success</button>
    </form>
 </div>

{% endblock content %}

user/templates/user/edit.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="card">
    {% for note in note_detail %}
    <div class="card-header">
        <a href="{% url 'users:edit_notes' note.id %}">{{ note.title }}</a>
    </div>
    <div class="card-body">
      <blockquote class="blockquote mb-0">
        <p>{{ note.description }}</p>
        <footer class="blockquote-footer">{{ note.writer }}</footer>
      </blockquote>
    </div>
    <form method="POST">
        <button type="submit" class="btn btn-danger" name="note_delete">delete</button>
    </from>
    {% endfor %}
</div>




<div class = "container">
    <form method="POST">
      {% csrf_token %}
      <h4>title</h4>
      <div class = "form-group">
        <input type = "text" class = "form-control" 
            id = "exampleFormControlInput1" name="new_title" placeholder = "title">
      </div>

      <h4>your subscribers</h4>
      <div class = "form-group">
        <select multiple class = "form-control" id = "exampleFormControlSelect2" name='subscribers'>
          {% for subscriber in subscribers %}
          <option>{{ subscriber }}</option>
          {% endfor %}
        </select>
      </div>
       
      <h4>note</h4>
      <div class = "form-group">
        <textarea class = "form-control" id = "exampleFormControlTextarea1" name="new_description" rows = "3"></textarea>
      </div>
      <button type="submit" class="btn btn-success">Success</button>
    </form>
</div>

{% endblock content %}

user/templates/user/login.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<form method="post" action="{% url 'users:login' %}">
    {% csrf_token %}
    <div class="form-group">
        <label for="{{ login_form.user_name.id_for_label }}">{{ login_form.user_name.label }}</label>
        {{ login_form.user_name }}
        {% for error in login_form.user_name.errors %}
            <p style="color: red;">{{ error }}</p>
        {% endfor %}
        <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
    </div>
    <div class="form-group">
        <label for="{{ login_form.password.id_for_label }}">{{ login_form.password.label }}</label>
        {{ login_form.password }}
        {% for error in login_form.password.errors %}
            <p style="color: red;">{{ error }}</p>
        {% endfor %}
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>

</form>

<a href="{% url 'users:register' %}"><button type="submit" class="btn btn-warning">not login? register here</button></a>

{% endblock content %}

user/templates/user/profile.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="card">
    {% for note in notes %}
    <div class="card-header">
        <a href="{% url 'users:edit_notes' note.id %}">{{ note.title }}</a>
    </div>
    <div class="card-body">
      <blockquote class="blockquote mb-0">
        <p>{{ note.description }}</p>
        <footer class="blockquote-footer">{{ note.writer }}</footer>
      </blockquote>
    </div>
    {% endfor %}
</div>
{% endblock content %}

user/templates/user/register.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <form method="post" action="{% url 'users:register' %}">
        {% csrf_token %}
        <div class="mb-3">
            <label for="{{ register_form.user_name.id_for_label }}" class="form-label">{{ register_form.user_name.label }}</label>
            {{ register_form.user_name }}
            {% for error in register_form.user_name.errors %}
                <p style="color: red;">{{ error }}</p>
            {% endfor %}          
        </div>
        <div class="mb-3">
            <label for="{{ register_form.email.id_for_label }} class="form-label"">{{ register_form.email.label }}</label>
            {{ register_form.email }}
            {% for error in register_form.email.errors %}
                <p style="color: red;">{{ error }}</p>
            {% endfor %}
        </div>
        <div class="mb-3">
            <label for="{{ register_form.password.id_for_label }} class="form-label"">{{ register_form.password.label }}</label>
            {{ register_form.password }}
            {% for error in register_form.password.errors %}
                <p style="color: red;">{{ error }}</p>
            {% endfor %}
        </div>
        <div class="mb-3">
            <label for="{{ register_form.re_password.id_for_label }} class="form-label"">{{ register_form.re_password.label }}</label>
            {{ register_form.re_password }}
            {% for error in register_form.re_password.errors %}
                <p style="color: red;">{{ error }}</p>
            {% endfor %}
        </div>
        <button type="submit" class="btn btn-primary">ثبت نام</button>
      </form>
      
{% endblock content %}